[versions]
kotlin = "2.1.20"
serialization="1.8.0"

[plugins]
kotlin-multiplatform = { version.ref = "kotlin", id = "org.jetbrains.kotlin.multiplatform" }
serialization={version.ref="kotlin",id="org.jetbrains.kotlin.plugin.serialization"}

[libraries]
sealization-json={version.ref="serialization",module="org.jetbrains.kotlinx:kotlinx-serialization-json"}

[bundles]
